knp_paginator:
    convert_exception: false
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: '@KnpPaginator/Pagination/tailwindcss_pagination.html.twig'
